jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
      with:
        path: proguard-main
    - continue-on-error: true
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - continue-on-error: true
      uses: eskatos/gradle-command-action@v1
      with:
        arguments: test :base:testAllJavaVersions :base:jacocoTestReport jar --info
        build-root-directory: proguard-main/
        wrapper-directory: proguard-main/
    - continue-on-error: true
      if: always()
      name: Publish Test Report
      uses: mikepenz/action-junit-report@v3
      with:
        report_paths: '**/build/test-results/test/TEST-*.xml'
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - windows-latest
name: Continuous Integration
on:
  repository_dispatch:
    types: trigger-ga___continuous_integration.yml
